project:
  type: website

website:
  title: "kyyeee.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: jekyll-theme-beautiful
    css: styles.css
    toc: true

editor: visual

